
services:
  app-hero-store:
    build: .
    container_name: hero_store_api
    tty: true
    stdin_open: true
    command: npm run dev
    image: hero-store-api:1.0
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_HOST: ${DB_HOST:-db}   # Usar o nome do serviço do banco no Docker
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME:-HeroDB}
      JWT_SECRET: ${JWT_SECRET:-secret}

  db:
    container_name: hero_store_db
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: HeroDB
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
